#!/bin/sh
  
# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.
# Author: Ivo
# Source: http://crunchbang.org/forums/viewtopic.php?pid=134749#p134749

initializeANSI()
{
  esc=""

  heejf="${esc}[38;2;236;0;140m";
  hyunf="${esc}[38;2;255;204;0m";
  hasef="${esc}[38;2;0;166;81m";
  yeojf="${esc}[38;2;244;111;31m";
  vivif="${esc}[38;2;225;152;180m";
  kimlf="${esc}[38;2;228;26;62m";
  jinsf="${esc}[38;2;20;36;176m"; 
  choef="${esc}[38;2;92;44;146m";
  yvesf="${esc}[38;2;126;0;47m";
  chuuf="${esc}[38;2;246;144;126m";
  gowof="${esc}[38;2;48;195;156m";
  olivf="${esc}[38;2;143;143;143m";

  blackb="${esc}[40m";   redb="${esc}[41m";    greenb="${esc}[42m"
  yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
  cyanb="${esc}[46m";    whiteb="${esc}[47m"

  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"

  reset="${esc}[0m"
}

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one.

initializeANSI

cat << EOF  
  
${boldon}${heejf}   ██████  ${reset} ${boldon}${hyunf}██████   ${reset}${boldon}${hasef}  ██████${reset} ${boldon}${yeojf}██████  ${reset} ${boldon}${vivif}  ██████${reset} ${boldon}${kimlf}  ███████${reset}
${boldon}${heejf}   ████████${reset} ${boldon}${hyunf}██    ██ ${reset}${boldon}${hasef}██      ${reset} ${boldon}${yeojf}██    ██${reset} ${boldon}${vivif}██████  ${reset} ${boldon}${kimlf}█████████${reset}
${heejf}   ██  ████${reset} ${hyunf}██  ████ ${reset}${hasef}████    ${reset} ${yeojf}████  ██${reset} ${vivif}████    ${reset} ${kimlf}█████    ${reset}
${heejf}   ██    ██${reset} ${hyunf}██████   ${reset}${hasef}████████${reset} ${yeojf}██████  ${reset} ${vivif}████████${reset} ${kimlf}██       ${reset} 
 
EOF
