#!/usr/bin/env bash
# Author: Ivo
# Source: http://crunchbang.org/forums/viewtopic.php?pid=134749#p134749

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

${heejf}  ████  ${reset} ${hyunf}██████  ${reset} ${hasef}  ██████${reset} ${yeojf}██████  ${reset} ${vivif}████████${reset} ${kimlf}████████${reset}
${heejf}██    ██${reset} ${hyunf}██    ██${reset} ${hasef}██      ${reset} ${yeojf}██    ██${reset} ${vivif}████████${reset} ${kimlf}██      ${reset}
${heejf}████████${reset} ${hyunf}██  ████${reset} ${hasef}██      ${reset} ${yeojf}██    ██${reset} ${vivif}██      ${reset} ${kimlf}██████  ${reset}
${heejf}██    ██${reset} ${hyunf}██████  ${reset} ${hasef}  ██████${reset} ${yeojf}██████  ${reset} ${vivif}████████${reset} ${kimlf}██      ${reset}

${jinsf}████████${reset} ${choef}██    ██${reset} ${yvesf}████████${reset} ${chuuf}████████${reset} ${gowof}██   ███${reset} ${olivf}██      ${reset}
${jinsf}██      ${reset} ${choef}██    ██${reset} ${yvesf}   ██   ${reset} ${chuuf}   ██   ${reset} ${gowof}█████   ${reset} ${olivf}██      ${reset}
${jinsf}██   ███${reset} ${choef}████████${reset} ${yvesf}   ██   ${reset} ${chuuf}██ ██   ${reset} ${gowof}█████   ${reset} ${olivf}██      ${reset}
${jinsf}████████${reset} ${choef}██    ██${reset} ${yvesf}████████${reset} ${chuuf}█████   ${reset} ${gowof}██   ███${reset} ${olivf}████████${reset}

EOF
