#!/bin/sh

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.
# Author: ed209
# Source: http://crunchbang.org/forums/viewtopic.php?pid=295676#p295676

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one. ■ ■ ▓ ■ ■ ■ ■ ■

initializeANSI

cat << EOF

${heejf}■■■■${reset}${heejf}■■${reset}   ${hyunf}■■■■${reset}${hyunf}■■${reset}   ${hasef}■■■■${reset}${hasef}■■${reset}   ${yeojf}■■■■${reset}${vivif}■■${reset}   ${vivif}■■■■${reset}${yeojf}■■${reset}   ${kimlf}■■■■${reset}${kimlf}■■${reset} 
${heejf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hyunf}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${hasef}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${hyunf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hasef}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${yeojf}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${hyunf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hasef}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${yeojf}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${heejf}■■■■${reset}${heejf}■■${reset}   ${hyunf}■■■■${reset}${hyunf}■■${reset}   ${hasef}■■■■${reset}${hasef}■■${reset}   ${yeojf}■■■■${reset}${vivif}■■${reset}   ${vivif}■■■■${reset}${yeojf}■■${reset}   ${kimlf}■■■■${reset}${kimlf}■■${reset} 
${heejf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hyunf}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${hasef}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${hyunf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hasef}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${yeojf}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${hyunf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hasef}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${yeojf}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${heejf}■■■■${reset}${heejf}■■${reset}   ${hyunf}■■■■${reset}${hyunf}■■${reset}   ${hasef}■■■■${reset}${hasef}■■${reset}   ${yeojf}■■■■${reset}${vivif}■■${reset}   ${vivif}■■■■${reset}${yeojf}■■${reset}   ${kimlf}■■■■${reset}${kimlf}■■${reset} 
${heejf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hyunf}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${hasef}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${hyunf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hasef}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${yeojf}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 
${hyunf}■■${reset}${hyunf}■■${reset}${heejf}■■${reset}   ${hasef}■■${reset}${hasef}■■${reset}${hyunf}■■${reset}   ${yeojf}■■${reset}${yeojf}■■${reset}${hasef}■■${reset}   ${kimlf}■■${reset}${vivif}■■${reset}${vivif}■■${reset}   ${vivif}■■${reset}${kimlf}■■${reset}${yeojf}■■${reset}   ${yeojf}■■${reset}${vivif}■■${reset}${kimlf}■■${reset} 

${jinsf}■■■■${reset}${jinsf}■■${reset}   ${choef}■■■■${reset}${choef}■■${reset}   ${yvesf}■■■■${reset}${yvesf}■■${reset}   ${chuuf}■■■■${reset}${gowof}■■${reset}   ${gowof}■■■■${reset}${chuuf}■■${reset}   ${olivf}■■■■${reset}${olivf}■■${reset} 
${jinsf}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${choef}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${yvesf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${choef}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${yvesf}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${chuuf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${choef}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${yvesf}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${chuuf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${jinsf}■■■■${reset}${jinsf}■■${reset}   ${choef}■■■■${reset}${choef}■■${reset}   ${yvesf}■■■■${reset}${yvesf}■■${reset}   ${chuuf}■■■■${reset}${gowof}■■${reset}   ${gowof}■■■■${reset}${chuuf}■■${reset}   ${olivf}■■■■${reset}${olivf}■■${reset} 
${jinsf}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${choef}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${yvesf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${choef}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${yvesf}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${chuuf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${choef}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${yvesf}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${chuuf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${jinsf}■■■■${reset}${jinsf}■■${reset}   ${choef}■■■■${reset}${choef}■■${reset}   ${yvesf}■■■■${reset}${yvesf}■■${reset}   ${chuuf}■■■■${reset}${gowof}■■${reset}   ${gowof}■■■■${reset}${chuuf}■■${reset}   ${olivf}■■■■${reset}${olivf}■■${reset} 
${jinsf}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${choef}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${yvesf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${choef}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${yvesf}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${chuuf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
${choef}■■${reset}${choef}■■${reset}${jinsf}■■${reset}   ${yvesf}■■${reset}${yvesf}■■${reset}${choef}■■${reset}   ${chuuf}■■${reset}${chuuf}■■${reset}${yvesf}■■${reset}   ${olivf}■■${reset}${gowof}■■${reset}${gowof}■■${reset}   ${gowof}■■${reset}${olivf}■■${reset}${chuuf}■■${reset}   ${chuuf}■■${reset}${gowof}■■${reset}${olivf}■■${reset} 
 
EOF
