#!/usr/bin/env bash

#   Daniel Crisman's ANSI color chart script from
#   The Bash Prompt HOWTO: 6.1. Colours
#   http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
#  
#   This function echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).

    T='•••••'   # The text for the color test
    
    echo -e "\n               heejf  hyunf  hasef  yeojf  vivif  kimlf  jinsf  choef  yvesf  chuuf  gowof  olivf";
    
    for FGs in '236;000;140m' '255;204;000m' '000;166;081m' '244;111;031m' '225;152;180m' '228;026;062m' '020;036;176m' '092;044;146m' '126;000;047m' '246;144;126m' '048;195;156m' '143;143;143m';
    
      do FG=${FGs// /}
      echo -en "\033[38;2;$FG\033[49m $FGs "
      
      for BG in '236;000;140m' '255;204;000m' '000;166;081m' '244;111;031m' '225;152;180m' '228;026;062m' '020;036;176m' '092;044;146m' '126;000;047m' '246;144;126m' '048;195;156m' '143;143;143m';
        do echo -en "\033[38;2;$FG\033[48;2;$BG $T $EINS";
      done
      echo;
    done
    echo
