#!/usr/bin/env bash

# Original: http://frexx.de/xterm-256-notes/
#           http://frexx.de/xterm-256-notes/data/colortable16.sh
# Modified by Aaron Griffin
# and further by Kazuo Teramoto

FGNAMES=('HEEJ' 'HYUN' 'HASE' 'YEOJ' 'VIVI' 'KIML' 'JINS' 'CHOE' 'YVES' 'CHUU' 'GOWO' 'OLIV')
BGNAMES=('HEEJ' 'HYUN' 'HASE' 'YEOJ' 'VIVI' 'KIML' 'JINS' 'CHOE' 'YVES' 'CHUU' 'GOWO' 'OLIV')
COLORS=('236;000;140m' '255;204;000m' '000;166;081m' '244;111;031m' '225;152;180m' '228;026;062m' '020;036;176m' '092;044;146m' '126;000;047m' '246;144;126m' '048;195;156m' '143;143;143m')

echo "      ┌──────────────────────────────────────────────────────────────────────────────────────────────────┐"
for b in {0..11}; do
  ((b>0)) && bg=${COLORS[b]}

  echo -en "\033[0m ${BGNAMES[b]} │ "
  
  for f in {0..11};
  do
    echo -en "\033[38;2;${COLORS[f]}\033[48;2;${COLORS[b]}  ${FGNAMES[f]}  "
  done

  echo -en "\033[0m │"
  echo -e "\033[0m"

  ((b<11)) &&
  echo "      ├──────────────────────────────────────────────────────────────────────────────────────────────────┤"
done
echo "      └──────────────────────────────────────────────────────────────────────────────────────────────────┘"
