#!/bin/bash
# Author: steampunknyanja
# Source: http://crunchbang.org/forums/viewtopic.php?pid=146715#p146715

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF
 ${heejf}  ██  ██   ${heejf}██    ${hyunf}  ██  ██   ${hyunf}██    ${hasef}  ██  ██   ${hasef}██    ${yeojf}  ██  ██   ${yeojf}██    ${vivif}  ██  ██   ${vivif}██    ${kimlf}  ██  ██   ${kimlf}██
 ${heejf}██████████ ${heejf}██    ${hyunf}██████████ ${hyunf}██    ${hasef}██████████ ${hasef}██    ${yeojf}██████████ ${yeojf}██    ${vivif}██████████ ${vivif}██    ${kimlf}██████████ ${kimlf}██
 ${heejf}  ██  ██   ${heejf}██    ${hyunf}  ██  ██   ${hyunf}██    ${hasef}  ██  ██   ${hasef}██    ${yeojf}  ██  ██   ${yeojf}██    ${vivif}  ██  ██   ${vivif}██    ${kimlf}  ██  ██   ${kimlf}██
 ${heejf}██████████       ${hyunf}██████████       ${hasef}██████████       ${yeojf}██████████       ${vivif}██████████       ${kimlf}██████████   
 ${heejf}  ██  ██   ${heejf}██    ${hyunf}  ██  ██   ${hyunf}██    ${hasef}  ██  ██   ${hasef}██    ${yeojf}  ██  ██   ${yeojf}██    ${vivif}  ██  ██   ${vivif}██    ${kimlf}  ██  ██   ${kimlf}██ 

 ${jinsf}  ██  ██   ${jinsf}██    ${choef}  ██  ██   ${choef}██    ${yvesf}  ██  ██   ${yvesf}██    ${chuuf}  ██  ██   ${chuuf}██    ${gowof}  ██  ██   ${gowof}██    ${olivf}  ██  ██   ${olivf}██
 ${jinsf}██████████ ${jinsf}██    ${choef}██████████ ${choef}██    ${yvesf}██████████ ${yvesf}██    ${chuuf}██████████ ${chuuf}██    ${gowof}██████████ ${gowof}██    ${olivf}██████████ ${olivf}██
 ${jinsf}  ██  ██   ${jinsf}██    ${choef}  ██  ██   ${choef}██    ${yvesf}  ██  ██   ${yvesf}██    ${chuuf}  ██  ██   ${chuuf}██    ${gowof}  ██  ██   ${gowof}██    ${olivf}  ██  ██   ${olivf}██
 ${jinsf}██████████       ${choef}██████████       ${yvesf}██████████       ${chuuf}██████████       ${gowof}██████████       ${olivf}██████████   
 ${jinsf}  ██  ██   ${jinsf}██    ${choef}  ██  ██   ${choef}██    ${yvesf}  ██  ██   ${yvesf}██    ${chuuf}  ██  ██   ${chuuf}██    ${gowof}  ██  ██   ${gowof}██    ${olivf}  ██  ██   ${olivf}██ 

EOF
