#!/usr/bin/env bash
# Author: thevdude
# Source: http://crunchbang.org/forums/viewtopic.php?pid=147530#p147530

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF
 ${heejf}▄█▄█▄ ${heejf}█ ${hyunf}▄█▄█▄ ${hyunf}█ ${hasef}▄█▄█▄ ${hasef}█ ${yeojf}▄█▄█▄ ${yeojf}█ ${vivif}▄█▄█▄ ${vivif}█ ${kimlf}▄█▄█▄ ${kimlf}█
 ${heejf}▄█▄█▄ ${heejf}▀ ${hyunf}▄█▄█▄ ${hyunf}▀ ${hasef}▄█▄█▄ ${hasef}▀ ${yeojf}▄█▄█▄ ${yeojf}▀ ${vivif}▄█▄█▄ ${vivif}▀ ${kimlf}▄█▄█▄ ${kimlf}▀
 ${heejf} ▀ ▀  ${heejf}▀ ${hyunf} ▀ ▀  ${hyunf}▀ ${hasef} ▀ ▀  ${hasef}▀ ${yeojf} ▀ ▀  ${yeojf}▀ ${vivif} ▀ ▀  ${vivif}▀ ${kimlf} ▀ ▀  ${kimlf}▀

 ${jinsf}▄█▄█▄ ${jinsf}█ ${choef}▄█▄█▄ ${choef}█ ${yvesf}▄█▄█▄ ${yvesf}█ ${chuuf}▄█▄█▄ ${chuuf}█ ${gowof}▄█▄█▄ ${gowof}█ ${olivf}▄█▄█▄ ${olivf}█
 ${jinsf}▄█▄█▄ ${jinsf}▀ ${choef}▄█▄█▄ ${choef}▀ ${yvesf}▄█▄█▄ ${yvesf}▀ ${chuuf}▄█▄█▄ ${chuuf}▀ ${gowof}▄█▄█▄ ${gowof}▀ ${olivf}▄█▄█▄ ${olivf}▀
 ${jinsf} ▀ ▀  ${jinsf}▀ ${choef} ▀ ▀  ${choef}▀ ${yvesf} ▀ ▀  ${yvesf}▀ ${chuuf} ▀ ▀  ${chuuf}▀ ${gowof} ▀ ▀  ${gowof}▀ ${olivf} ▀ ▀  ${olivf}▀

EOF
