#!/usr/bin/env bash
# Author: gutterslob
# Source: http://crunchbang.org/forums/viewtopic.php?pid=148022#p148022

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

 ${heejf}  ██  ██   ${hyunf}   ██  ██   ${hasef}   ██  ██   ${yeojf}   ██  ██   ${vivif}   ██  ██   ${kimlf}   ██  ██
 ${heejf}██████████ ${hyunf} ██████████ ${hasef} ██████████ ${yeojf} ██████████ ${vivif} ██████████ ${kimlf} ██████████
 ${heejf}  ██████   ${hyunf}   ██████   ${hasef}   ██████   ${yeojf}   ██████   ${vivif}   ██████   ${kimlf}   ██████
 ${heejf}██████████ ${hyunf} ██████████ ${hasef} ██████████ ${yeojf} ██████████ ${vivif} ██████████ ${kimlf} ██████████
 ${heejf}  ██  ██   ${hyunf}   ██  ██   ${hasef}   ██  ██   ${yeojf}   ██  ██   ${vivif}   ██  ██   ${kimlf}   ██  ██

 ${jinsf}  ██  ██   ${choef}   ██  ██   ${yvesf}   ██  ██   ${chuuf}   ██  ██   ${gowof}   ██  ██   ${olivf}   ██  ██
 ${jinsf}██████████ ${choef} ██████████ ${yvesf} ██████████ ${chuuf} ██████████ ${gowof} ██████████ ${olivf} ██████████
 ${jinsf}  ██████   ${choef}   ██████   ${yvesf}   ██████   ${chuuf}   ██████   ${gowof}   ██████   ${olivf}   ██████
 ${jinsf}██████████ ${choef} ██████████ ${yvesf} ██████████ ${chuuf} ██████████ ${gowof} ██████████ ${olivf} ██████████
 ${jinsf}  ██  ██   ${choef}   ██  ██   ${yvesf}   ██  ██   ${chuuf}   ██  ██   ${gowof}   ██  ██   ${olivf}   ██  ██

EOF
