#!/bin/bash
# ANSI color scheme script by pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=144011#p144011
# Initializing mod by lolilolicon from Archlinux

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

 ${heejf}█-----$bld█  $rst${hyunf}█-----$bld█$rst  ${hasef}█-----$bld█$rst  ${yeojf}█-----$bld█$rst  ${vivif}█-----$bld█$rst  ${kimlf}█-----$bld█$rst
  ${heejf}█---$bld█$rst    ${hyunf}█---$bld█$rst    ${hasef}█---$bld█$rst    ${yeojf}█---$bld█$rst    ${vivif}█---$bld█$rst    ${kimlf}█---$bld█$rst
  ${heejf} █-$bld█$rst     ${hyunf} █-$bld█$rst     ${hasef} █-$bld█$rst     ${yeojf} █-$bld█$rst     ${vivif} █-$bld█$rst     ${kimlf} █-$bld█$rst
    ${heejf}█$rst        ${hyunf}█$rst        ${hasef}█$rst        ${yeojf}█$rst        ${vivif}█$rst        ${kimlf}█$rst
   ${heejf}$bld█-$rst${heejf}█$rst      ${hyunf}$bld█_$rst${hyunf}█$rst      ${hasef}$bld█-$rst${hasef}█$rst      ${yeojf}$bld█-$rst${yeojf}█$rst      ${vivif}$bld█-$rst${vivif}█$rst      ${kimlf}$bld█-$rst${kimlf}█$rst
  ${heejf}$bld█---$rst${heejf}█$rst    ${hyunf}$bld█---$rst${hyunf}█$rst    ${hasef}$bld█---$rst${hasef}█$rst    ${yeojf}$bld█---$rst${yeojf}█$rst    ${vivif}$bld█---$rst${vivif}█$rst    ${kimlf}$bld█---$rst${kimlf}█$rst 
 ${heejf}$bld█-----$rst${heejf}█$rst  ${hyunf}$bld█-----$rst${hyunf}█$rst  ${hasef}$bld█-----$rst${hasef}█$rst  ${yeojf}$bld█-----$rst${yeojf}█$rst  ${vivif}$bld█-----$rst${vivif}█$rst  ${kimlf}$bld█-----$rst${kimlf}█$rst
  ${heejf}$bld█---$rst${heejf}█$rst    ${hyunf}$bld█---$rst${hyunf}█$rst    ${hasef}$bld█---$rst${hasef}█$rst    ${yeojf}$bld█---$rst${yeojf}█$rst    ${vivif}$bld█---$rst${vivif}█$rst    ${kimlf}$bld█---$rst${kimlf}█$rst
   ${heejf}$bld█-$rst${heejf}█$rst      ${hyunf}$bld█-$rst${hyunf}█$rst      ${hasef}$bld█-$rst${hasef}█$rst      ${yeojf}$bld█-$rst${yeojf}█$rst      ${vivif}$bld█-$rst${vivif}█$rst      ${kimlf}$bld█-$rst${kimlf}█$rst
    ${heejf}$bld█$rst        ${hyunf}$bld█$rst        ${hasef}$bld█$rst        ${yeojf}$bld█$rst        ${vivif}$bld█$rst        ${kimlf}$bld█$rst
   ${heejf}█-$bld█$rst      ${hyunf}█-$bld█$rst      ${hasef}█-$bld█$rst      ${yeojf}█-$bld█$rst      ${vivif}█-$bld█$rst      ${kimlf}█-$bld█$rst
  ${heejf}█---$bld█$rst    ${hyunf}█---$bld█$rst    ${hasef}█---$bld█$rst    ${yeojf}█---$bld█$rst    ${vivif}█---$bld█$rst    ${kimlf}█---$bld█$rst
 ${heejf}█-----$bld█  $rst${hyunf}█-----$bld█$rst  ${hasef}█-----$bld█$rst  ${yeojf}█-----$bld█$rst  ${vivif}█-----$bld█$rst  ${kimlf}█-----$bld█$rst
  ${heejf}█---$bld█$rst    ${hyunf}█---$bld█$rst    ${hasef}█---$bld█$rst    ${yeojf}█---$bld█$rst    ${vivif}█---$bld█$rst    ${kimlf}█---$bld█$rst
  ${heejf} █-$bld█$rst     ${hyunf} █-$bld█$rst     ${hasef} █-$bld█$rst     ${yeojf} █-$bld█$rst     ${vivif} █-$bld█$rst     ${kimlf} █-$bld█$rst
    ${heejf}█$rst        ${hyunf}█$rst        ${hasef}█$rst        ${yeojf}█$rst        ${vivif}█$rst        ${kimlf}█$rst
   ${heejf}$bld█-$rst${heejf}█$rst      ${hyunf}$bld█_$rst${hyunf}█$rst      ${hasef}$bld█-$rst${hasef}█$rst      ${yeojf}$bld█-$rst${yeojf}█$rst      ${vivif}$bld█-$rst${vivif}█$rst      ${kimlf}$bld█-$rst${kimlf}█$rst
  ${heejf}$bld█---$rst${heejf}█$rst    ${hyunf}$bld█---$rst${hyunf}█$rst    ${hasef}$bld█---$rst${hasef}█$rst    ${yeojf}$bld█---$rst${yeojf}█$rst    ${vivif}$bld█---$rst${vivif}█$rst    ${kimlf}$bld█---$rst${kimlf}█$rst 
 ${heejf}$bld█-----$rst${heejf}█$rst  ${hyunf}$bld█-----$rst${hyunf}█$rst  ${hasef}$bld█-----$rst${hasef}█$rst  ${yeojf}$bld█-----$rst${yeojf}█$rst  ${vivif}$bld█-----$rst${vivif}█$rst  ${kimlf}$bld█-----$rst${kimlf}█$rst
  ${heejf}$bld█---$rst${heejf}█$rst    ${hyunf}$bld█---$rst${hyunf}█$rst    ${hasef}$bld█---$rst${hasef}█$rst    ${yeojf}$bld█---$rst${yeojf}█$rst    ${vivif}$bld█---$rst${vivif}█$rst    ${kimlf}$bld█---$rst${kimlf}█$rst
   ${heejf}$bld█-$rst${heejf}█$rst      ${hyunf}$bld█-$rst${hyunf}█$rst      ${hasef}$bld█-$rst${hasef}█$rst      ${yeojf}$bld█-$rst${yeojf}█$rst      ${vivif}$bld█-$rst${vivif}█$rst      ${kimlf}$bld█-$rst${kimlf}█$rst
    ${heejf}$bld█$rst        ${hyunf}$bld█$rst        ${hasef}$bld█$rst        ${yeojf}$bld█$rst        ${vivif}$bld█$rst        ${kimlf}$bld█$rst
   ${heejf}█-$bld█$rst      ${hyunf}█-$bld█$rst      ${hasef}█-$bld█$rst      ${yeojf}█-$bld█$rst      ${vivif}█-$bld█$rst      ${kimlf}█-$bld█$rst
  ${heejf}█---$bld█$rst    ${hyunf}█---$bld█$rst    ${hasef}█---$bld█$rst    ${yeojf}█---$bld█$rst    ${vivif}█---$bld█$rst    ${kimlf}█---$bld█$rst
 ${heejf}█-----$bld█  $rst${hyunf}█-----$bld█$rst  ${hasef}█-----$bld█$rst  ${yeojf}█-----$bld█$rst  ${vivif}█-----$bld█$rst  ${kimlf}█-----$bld█$rst

 ${jinsf}█-----$bld█  $rst${choef}█-----$bld█$rst  ${yvesf}█-----$bld█$rst  ${chuuf}█-----$bld█$rst  ${gowof}█-----$bld█$rst  ${olivf}█-----$bld█$rst
  ${jinsf}█---$bld█$rst    ${choef}█---$bld█$rst    ${yvesf}█---$bld█$rst    ${chuuf}█---$bld█$rst    ${gowof}█---$bld█$rst    ${olivf}█---$bld█$rst
  ${jinsf} █-$bld█$rst     ${choef} █-$bld█$rst     ${yvesf} █-$bld█$rst     ${chuuf} █-$bld█$rst     ${gowof} █-$bld█$rst     ${olivf} █-$bld█$rst
    ${jinsf}█$rst        ${choef}█$rst        ${yvesf}█$rst        ${chuuf}█$rst        ${gowof}█$rst        ${olivf}█$rst
   ${jinsf}$bld█-$rst${jinsf}█$rst      ${choef}$bld█_$rst${choef}█$rst      ${yvesf}$bld█-$rst${yvesf}█$rst      ${chuuf}$bld█-$rst${chuuf}█$rst      ${gowof}$bld█-$rst${gowof}█$rst      ${olivf}$bld█-$rst${olivf}█$rst
  ${jinsf}$bld█---$rst${jinsf}█$rst    ${choef}$bld█---$rst${choef}█$rst    ${yvesf}$bld█---$rst${yvesf}█$rst    ${chuuf}$bld█---$rst${chuuf}█$rst    ${gowof}$bld█---$rst${gowof}█$rst    ${olivf}$bld█---$rst${olivf}█$rst 
 ${jinsf}$bld█-----$rst${jinsf}█$rst  ${choef}$bld█-----$rst${choef}█$rst  ${yvesf}$bld█-----$rst${yvesf}█$rst  ${chuuf}$bld█-----$rst${chuuf}█$rst  ${gowof}$bld█-----$rst${gowof}█$rst  ${olivf}$bld█-----$rst${olivf}█$rst
  ${jinsf}$bld█---$rst${jinsf}█$rst    ${choef}$bld█---$rst${choef}█$rst    ${yvesf}$bld█---$rst${yvesf}█$rst    ${chuuf}$bld█---$rst${chuuf}█$rst    ${gowof}$bld█---$rst${gowof}█$rst    ${olivf}$bld█---$rst${olivf}█$rst
   ${jinsf}$bld█-$rst${jinsf}█$rst      ${choef}$bld█-$rst${choef}█$rst      ${yvesf}$bld█-$rst${yvesf}█$rst      ${chuuf}$bld█-$rst${chuuf}█$rst      ${gowof}$bld█-$rst${gowof}█$rst      ${olivf}$bld█-$rst${olivf}█$rst
    ${jinsf}$bld█$rst        ${choef}$bld█$rst        ${yvesf}$bld█$rst        ${chuuf}$bld█$rst        ${gowof}$bld█$rst        ${olivf}$bld█$rst
   ${jinsf}█-$bld█$rst      ${choef}█-$bld█$rst      ${yvesf}█-$bld█$rst      ${chuuf}█-$bld█$rst      ${gowof}█-$bld█$rst      ${olivf}█-$bld█$rst
  ${jinsf}█---$bld█$rst    ${choef}█---$bld█$rst    ${yvesf}█---$bld█$rst    ${chuuf}█---$bld█$rst    ${gowof}█---$bld█$rst    ${olivf}█---$bld█$rst
 ${jinsf}█-----$bld█  $rst${choef}█-----$bld█$rst  ${yvesf}█-----$bld█$rst  ${chuuf}█-----$bld█$rst  ${gowof}█-----$bld█$rst  ${olivf}█-----$bld█$rst
 ${jinsf}█-----$bld█  $rst${choef}█-----$bld█$rst  ${yvesf}█-----$bld█$rst  ${chuuf}█-----$bld█$rst  ${gowof}█-----$bld█$rst  ${olivf}█-----$bld█$rst
  ${jinsf}█---$bld█$rst    ${choef}█---$bld█$rst    ${yvesf}█---$bld█$rst    ${chuuf}█---$bld█$rst    ${gowof}█---$bld█$rst    ${olivf}█---$bld█$rst
  ${jinsf} █-$bld█$rst     ${choef} █-$bld█$rst     ${yvesf} █-$bld█$rst     ${chuuf} █-$bld█$rst     ${gowof} █-$bld█$rst     ${olivf} █-$bld█$rst
    ${jinsf}█$rst        ${choef}█$rst        ${yvesf}█$rst        ${chuuf}█$rst        ${gowof}█$rst        ${olivf}█$rst
   ${jinsf}$bld█-$rst${jinsf}█$rst      ${choef}$bld█_$rst${choef}█$rst      ${yvesf}$bld█-$rst${yvesf}█$rst      ${chuuf}$bld█-$rst${chuuf}█$rst      ${gowof}$bld█-$rst${gowof}█$rst      ${olivf}$bld█-$rst${olivf}█$rst
  ${jinsf}$bld█---$rst${jinsf}█$rst    ${choef}$bld█---$rst${choef}█$rst    ${yvesf}$bld█---$rst${yvesf}█$rst    ${chuuf}$bld█---$rst${chuuf}█$rst    ${gowof}$bld█---$rst${gowof}█$rst    ${olivf}$bld█---$rst${olivf}█$rst 
 ${jinsf}$bld█-----$rst${jinsf}█$rst  ${choef}$bld█-----$rst${choef}█$rst  ${yvesf}$bld█-----$rst${yvesf}█$rst  ${chuuf}$bld█-----$rst${chuuf}█$rst  ${gowof}$bld█-----$rst${gowof}█$rst  ${olivf}$bld█-----$rst${olivf}█$rst
  ${jinsf}$bld█---$rst${jinsf}█$rst    ${choef}$bld█---$rst${choef}█$rst    ${yvesf}$bld█---$rst${yvesf}█$rst    ${chuuf}$bld█---$rst${chuuf}█$rst    ${gowof}$bld█---$rst${gowof}█$rst    ${olivf}$bld█---$rst${olivf}█$rst
   ${jinsf}$bld█-$rst${jinsf}█$rst      ${choef}$bld█-$rst${choef}█$rst      ${yvesf}$bld█-$rst${yvesf}█$rst      ${chuuf}$bld█-$rst${chuuf}█$rst      ${gowof}$bld█-$rst${gowof}█$rst      ${olivf}$bld█-$rst${olivf}█$rst
    ${jinsf}$bld█$rst        ${choef}$bld█$rst        ${yvesf}$bld█$rst        ${chuuf}$bld█$rst        ${gowof}$bld█$rst        ${olivf}$bld█$rst
   ${jinsf}█-$bld█$rst      ${choef}█-$bld█$rst      ${yvesf}█-$bld█$rst      ${chuuf}█-$bld█$rst      ${gowof}█-$bld█$rst      ${olivf}█-$bld█$rst
  ${jinsf}█---$bld█$rst    ${choef}█---$bld█$rst    ${yvesf}█---$bld█$rst    ${chuuf}█---$bld█$rst    ${gowof}█---$bld█$rst    ${olivf}█---$bld█$rst
 ${jinsf}█-----$bld█  $rst${choef}█-----$bld█$rst  ${yvesf}█-----$bld█$rst  ${chuuf}█-----$bld█$rst  ${gowof}█-----$bld█$rst  ${olivf}█-----$bld█$rst
  
EOF
