#!/bin/bash

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF
 ${white}╔══════════════════════════════════════════════════════════════════╗
 ${white}║ ${heejf}  ▄█ █▄${reset}    ${hyunf}  ▄█ █▄${reset}    ${hasef}  ▄█ █▄${reset}    ${yeojf}  ▄█ █▄${reset}    ${vivif}  ▄█ █▄${reset}    ${kimlf}  ▄█ █▄${reset}   ${white}║
 ${white}║ ${boldon}${heejf}▄█◄► ◄►█▄${reset}  ${boldon}${hyunf}▄█◄► ◄►█▄${reset}  ${boldon}${hasef}▄█◄► ◄►█▄${reset}  ${boldon}${yeojf}▄█◄► ◄►█▄${reset}  ${boldon}${vivif}▄█◄► ◄►█▄${reset}  ${boldon}${kimlf}▄█◄► ◄►█▄${reset} ${white}║
 ${white}║ ${boldon}${heejf}▀█    █▀${reset}  ${boldon}${hyunf}▀█    █▀${reset}  ${boldon}${hasef}▀█    █▀${reset}  ${boldon}${yeojf}▀█    █▀${reset}  ${boldon}${vivif}▀█    █▀${reset}  ${boldon}${kimlf}▀█    █▀${reset} ${white}║
 ${white}║ ${heejf}  ▀█ █▀${reset}    ${hyunf}  ▀█ █▀${reset}    ${hasef}  ▀█ █▀${reset}    ${yeojf}  ▀█ █▀${reset}    ${vivif}  ▀█ █▀${reset}    ${kimlf}  ▀█ █▀${reset}   ${white}║
 ${white}║ ${jinsf}  ▄█ █▄${reset}    ${choef}  ▄█ █▄${reset}    ${yvesf}  ▄█ █▄${reset}    ${chuuf}  ▄█ █▄${reset}    ${gowof}  ▄█ █▄${reset}    ${olivf}  ▄█ █▄${reset}   ${white}║
 ${white}║ ${boldon}${jinsf}▄█◄► ◄►█▄${reset}  ${boldon}${choef}▄█◄► ◄►█▄${reset}  ${boldon}${yvesf}▄█◄► ◄►█▄${reset}  ${boldon}${chuuf}▄█◄► ◄►█▄${reset}  ${boldon}${gowof}▄█◄► ◄►█▄${reset}  ${boldon}${olivf}▄█◄► ◄►█▄${reset} ${white}║
 ${white}║ ${boldon}${jinsf}▀█    █▀${reset}  ${boldon}${choef}▀█    █▀${reset}  ${boldon}${yvesf}▀█    █▀${reset}  ${boldon}${chuuf}▀█    █▀${reset}  ${boldon}${gowof}▀█    █▀${reset}  ${boldon}${olivf}▀█    █▀${reset} ${white}║
 ${white}║ ${jinsf}  ▀█ █▀${reset}    ${choef}  ▀█ █▀${reset}    ${yvesf}  ▀█ █▀${reset}    ${chuuf}  ▀█ █▀${reset}    ${gowof}  ▀█ █▀${reset}    ${olivf}  ▀█ █▀${reset}   ${white}║
 ${white}╚══════════════════════════════════════════════════════════════════╝
EOF
