#!/bin/bash

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

 ${heejf}▒▒▒▒${reset} ${boldon}${heejf}▒▒${reset}   ${hyunf}▒▒▒▒${reset} ${boldon}${hyunf}▒▒${reset}   ${hasef}▒▒▒▒${reset} ${boldon}${hasef}▒▒${reset}   ${yeojf}▒▒▒▒${reset} ${boldon}${yeojf}▒▒${reset}   ${vivif}▒▒▒▒${reset} ${boldon}${vivif}▒▒${reset}   ${kimlf}▒▒▒▒${reset} ${boldon}${kimlf}▒▒${reset} 
 ${heejf}▒▒ ■${reset} ${boldon}${heejf}▒▒${reset}   ${hyunf}▒▒ ■${reset} ${boldon}${hyunf}▒▒${reset}   ${hasef}▒▒ ■${reset} ${boldon}${hasef}▒▒${reset}   ${yeojf}▒▒ ■${reset} ${boldon}${yeojf}▒▒${reset}   ${vivif}▒▒ ■${reset} ${boldon}${vivif}▒▒${reset}   ${kimlf}▒▒ ■${reset} ${boldon}${kimlf}▒▒${reset}  
 ${heejf}▒▒ ${reset}${boldon}${heejf}▒▒▒▒${reset}   ${hyunf}▒▒ ${reset}${boldon}${hyunf}▒▒▒▒${reset}   ${hasef}▒▒ ${reset}${boldon}${hasef}▒▒▒▒${reset}   ${yeojf}▒▒ ${reset}${boldon}${yeojf}▒▒▒▒${reset}   ${vivif}▒▒ ${reset}${boldon}${vivif}▒▒▒▒${reset}   ${kimlf}▒▒ ${reset}${boldon}${kimlf}▒▒▒▒${reset}

 ${jinsf}▒▒▒▒${reset} ${boldon}${jinsf}▒▒${reset}   ${choef}▒▒▒▒${reset} ${boldon}${choef}▒▒${reset}   ${yvesf}▒▒▒▒${reset} ${boldon}${yvesf}▒▒${reset}   ${chuuf}▒▒▒▒${reset} ${boldon}${chuuf}▒▒${reset}   ${gowof}▒▒▒▒${reset} ${boldon}${gowof}▒▒${reset}   ${olivf}▒▒▒▒${reset} ${boldon}${olivf}▒▒${reset} 
 ${jinsf}▒▒ ■${reset} ${boldon}${jinsf}▒▒${reset}   ${choef}▒▒ ■${reset} ${boldon}${choef}▒▒${reset}   ${yvesf}▒▒ ■${reset} ${boldon}${yvesf}▒▒${reset}   ${chuuf}▒▒ ■${reset} ${boldon}${chuuf}▒▒${reset}   ${gowof}▒▒ ■${reset} ${boldon}${gowof}▒▒${reset}   ${olivf}▒▒ ■${reset} ${boldon}${olivf}▒▒${reset}  
 ${jinsf}▒▒ ${reset}${boldon}${jinsf}▒▒▒▒${reset}   ${choef}▒▒ ${reset}${boldon}${choef}▒▒▒▒${reset}   ${yvesf}▒▒ ${reset}${boldon}${yvesf}▒▒▒▒${reset}   ${chuuf}▒▒ ${reset}${boldon}${chuuf}▒▒▒▒${reset}   ${gowof}▒▒ ${reset}${boldon}${gowof}▒▒▒▒${reset}   ${olivf}▒▒ ${reset}${boldon}${olivf}▒▒▒▒${reset}

EOF
