#!/usr/bin/env bash

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

${heejf}██████████${reset}  ${hyunf}██        ${reset}  ${hasef}██████████${reset}  ${yeojf}██████████${reset}  ${vivif}██████████${reset}  ${kimlf}██      ██${reset}
${heejf}        ██${reset}  ${hyunf}██        ${reset}  ${hasef}██        ${reset}  ${yeojf}        ██${reset}  ${vivif}██      ██${reset}  ${kimlf}██      ██${reset}
${heejf}        ██${reset}  ${hyunf}██        ${reset}  ${hasef}██        ${reset}  ${yeojf}██████████${reset}  ${vivif}██      ██${reset}  ${kimlf}██████████${reset}
${heejf}        ██${reset}  ${hyunf}██        ${reset}  ${hasef}██        ${reset}  ${yeojf}██        ${reset}  ${vivif}██      ██${reset}  ${kimlf}██      ██${reset}
${heejf}        ██${reset}  ${hyunf}██████████${reset}  ${hasef}██████████${reset}  ${yeojf}██████████${reset}  ${vivif}██████████${reset}  ${kimlf}██████████${reset}

${jinsf}    ██    ${reset}  ${choef}  ██████  ${reset}  ${yvesf}██████████${reset}  ${chuuf}    ██    ${reset}  ${gowof}██████████${reset}  ${olivf}██████████${reset}
${jinsf}   ████   ${reset}  ${choef}██      ██${reset}  ${yvesf}   ████   ${reset}  ${chuuf}██████████${reset}  ${gowof}        ██${reset}  ${olivf}██         ${reset}
${jinsf}  ██  ██  ${reset}  ${choef}██      ██${reset}  ${yvesf}  ██████  ${reset}  ${chuuf}  ██████  ${reset}  ${gowof}  ████████${reset}  ${olivf}██████████${reset}
${jinsf} ██    ██ ${reset}  ${choef}██      ██${reset}  ${yvesf} ███  ███ ${reset}  ${chuuf} ███  ███ ${reset}  ${gowof}        ██${reset}  ${olivf}██        ${reset}
${jinsf}██      ██${reset}  ${choef}  ██████  ${reset}  ${yvesf}███    ███${reset}  ${chuuf}███    ███${reset}  ${gowof}        ██${reset}  ${olivf}██████████${reset}

EOF
