#!/usr/bin/env bash
# ANSI color scheme script by pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=157979#p157979
# Initializing mod by lolilolicon from Archlinux

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

$heejf    ▄▄▄      $hyunf    ▄▄▄      $hasef    ▄▄▄      $yeojf    ▄▄▄      $vivif    ▄▄▄      $kimlf    ▄▄▄
$heejf   ▀█▀██  ▄  $hyunf   ▀█▀██  ▄  $hasef   ▀█▀██  ▄  $yeojf   ▀█▀██  ▄  $vivif   ▀█▀██  ▄  $kimlf   ▀█▀██  ▄
$heejf ▀▄██████▀   $hyunf ▀▄██████▀   $hasef ▀▄██████▀   $yeojf ▀▄██████▀   $vivif ▀▄██████▀   $kimlf ▀▄██████▀
$heejf    ▀█████   $hyunf    ▀█████   $hasef    ▀█████   $yeojf    ▀█████   $vivif    ▀█████   $kimlf    ▀█████
$heejf       ▀▀▀▀▄ $hyunf       ▀▀▀▀▄ $hasef       ▀▀▀▀▄ $yeojf       ▀▀▀▀▄ $vivif       ▀▀▀▀▄ $kimlf       ▀▀▀▀▄

$jinsf    ▄▄▄      $choef    ▄▄▄      $yvesf    ▄▄▄      $chuuf    ▄▄▄      $gowof    ▄▄▄      $olivf    ▄▄▄
$jinsf   ▀█▀██  ▄  $choef   ▀█▀██  ▄  $yvesf   ▀█▀██  ▄  $chuuf   ▀█▀██  ▄  $gowof   ▀█▀██  ▄  $olivf   ▀█▀██  ▄
$jinsf ▀▄██████▀   $choef ▀▄██████▀   $yvesf ▀▄██████▀   $chuuf ▀▄██████▀   $gowof ▀▄██████▀   $olivf ▀▄██████▀
$jinsf    ▀█████   $choef    ▀█████   $yvesf    ▀█████   $chuuf    ▀█████   $gowof    ▀█████   $olivf    ▀█████
$jinsf       ▀▀▀▀▄ $choef       ▀▀▀▀▄ $yvesf       ▀▀▀▀▄ $chuuf       ▀▀▀▀▄ $gowof       ▀▀▀▀▄ $olivf       ▀▀▀▀▄
EOF
