#!/usr/bin/env bash

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

$heejf  ▄▄        ▄▄   $hyunf  ▄▄        ▄▄   $hasef  ▄▄        ▄▄   $yeojf  ▄▄        ▄▄   $vivif  ▄▄        ▄▄   $kimlf  ▄▄        ▄▄
$heejf▄█████▄  ▄█████▄ $hyunf▄█████▄  ▄█████▄ $hasef▄█████▄  ▄█████▄ $yeojf▄█████▄  ▄█████▄ $vivif▄█████▄  ▄█████▄ $kimlf▄█████▄  ▄█████▄
$heejf███████▄▄███████ $hyunf███████▄▄███████ $hasef███████▄▄███████ $yeojf███████▄▄███████ $vivif███████▄▄███████ $kimlf███████▄▄███████
$heejf████████████████ $hyunf████████████████ $hasef████████████████ $yeojf████████████████ $vivif████████████████ $kimlf████████████████
$heejf████████████████ $hyunf████████████████ $hasef████████████████ $yeojf████████████████ $vivif████████████████ $kimlf████████████████
$heejf████████████████ $hyunf████████████████ $hasef████████████████ $yeojf████████████████ $vivif████████████████ $kimlf████████████████
$heejf  ████████████   $hyunf  ████████████   $hasef  ████████████   $yeojf  ████████████   $vivif  ████████████   $kimlf  ████████████
$heejf    ████████     $hyunf    ████████     $hasef    ████████     $yeojf    ████████     $vivif    ████████     $kimlf    ████████
$heejf      ████       $hyunf      ████       $hasef      ████       $yeojf      ████       $vivif      ████       $kimlf      ████

$jinsf  ▄▄        ▄▄   $choef  ▄▄        ▄▄   $yvesf  ▄▄        ▄▄   $chuuf  ▄▄        ▄▄   $gowof  ▄▄        ▄▄   $olivf  ▄▄        ▄▄
$jinsf▄█████▄  ▄█████▄ $choef▄█████▄  ▄█████▄ $yvesf▄█████▄  ▄█████▄ $chuuf▄█████▄  ▄█████▄ $gowof▄█████▄  ▄█████▄ $olivf▄█████▄  ▄█████▄
$jinsf███████▄▄███████ $choef███████▄▄███████ $yvesf███████▄▄███████ $chuuf███████▄▄███████ $gowof███████▄▄███████ $olivf███████▄▄███████
$jinsf████████████████ $choef████████████████ $yvesf████████████████ $chuuf████████████████ $gowof████████████████ $olivf████████████████
$jinsf████████████████ $choef████████████████ $yvesf████████████████ $chuuf████████████████ $gowof████████████████ $olivf████████████████
$jinsf████████████████ $choef████████████████ $yvesf████████████████ $chuuf████████████████ $gowof████████████████ $olivf████████████████
$jinsf  ████████████   $choef  ████████████   $yvesf  ████████████   $chuuf  ████████████   $gowof  ████████████   $olivf  ████████████
$jinsf    ████████     $choef    ████████     $yvesf    ████████     $chuuf    ████████     $gowof    ████████     $olivf    ████████
$jinsf      ████       $choef      ████       $yvesf      ████       $chuuf      ████       $gowof      ████       $olivf      ████

EOF
