#!/bin/env bash
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh

initializeANSI

cat << EOF
 
 ${white} ██          ████      ████    ████████     ██    ${heejf}       ██ ${reset}
 ${white} ██        ██    ██  ██    ██  ██    ██    ████   ${heejf}     ██   ${reset}
 ${white} ██        ██    ██  ██    ██  ██    ██   ██  ██  ${heejf}   ██     ${reset}
 ${white} ████████    ████      ████    ██    ██  ████████ ${heejf} ██       ${reset}

EOF
