#!/usr/bin/env bash
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh

initializeANSI

cat << EOF

 ${heejf} ████████ ${hyunf} ████████ ${hasef} ████████ ${yeojf} ████████ ${vivif} ████████
 ${heejf} ████████ ${hyunf} ████████ ${hasef} ████████ ${yeojf} ████████ ${vivif} ████████
 ${heejf} ████████ ${hyunf} ████████ ${hasef} ████████ ${yeojf} ████████ ${vivif} ████████
 ${heejf} ████████ ${hyunf} ████████ ${hasef} ████████ ${yeojf} ████████ ${vivif} ████████

 ${kimlf} ▗▟████▙▖ ${jinsf} ▗▟████▙▖ ${choef} ▗▟████▙▖
 ${kimlf} ████████ ${jinsf} ████████ ${choef} ████████
 ${kimlf} ████████ ${jinsf} ████████ ${choef} ████████
 ${kimlf} ▝▜████▛▘ ${jinsf} ▝▜████▛▘ ${choef} ▝▜████▛▘

 ${yvesf}    ██    ${chuuf}    ██    ${gowof} ████████ ${olivf}    ██
 ${yvesf}   ████   ${chuuf}   ████   ${gowof}  ██████  ${olivf}   ████
 ${yvesf}  ██████  ${chuuf}  ██████  ${gowof}   ████   ${olivf}  ██████
 ${yvesf} ████████ ${chuuf} ████████ ${gowof}    ██    ${olivf} ████████

EOF
