#!/usr/bin/env bash
# Author: gutterslob
# Source: http://crunchbang.org/forums/viewtopic.php?pid=130590#p130590

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

              ${reset}${blackf}|               |               |               |               |${reset}
   ${heejf}█     █${reset}    ${blackf}|${reset}    ${hyunf}█     █${reset}    ${blackf}|${reset}    ${hasef}█     █${reset}    ${blackf}|${reset}    ${yeojf}█     █${reset}    ${blackf}|${reset}    ${vivif}█     █${reset}    ${blackf}|${reset}    ${kimlf}█     █${reset}
   ${heejf}███████${reset}    ${blackf}|${reset}    ${hyunf}███████${reset}    ${blackf}|${reset}    ${hasef}███████${reset}    ${blackf}|${reset}    ${yeojf}███████${reset}    ${blackf}|${reset}    ${vivif}███████${reset}    ${blackf}|${reset}    ${kimlf}███████${reset}
 ${heejf}███${boldon}${heejb}██${reset}${heejf}█${boldon}${heejb}██${reset}${heejf}███${reset}  ${blackf}|${reset}  ${hyunf}███${boldon}${hyunb}██${reset}${hyunf}█${boldon}${hyunb}██${reset}${hyunf}███${reset}  ${blackf}|${reset}  ${hasef}███${boldon}${haseb}██${reset}${hasef}█${boldon}${haseb}██${reset}${hasef}███${reset}  ${blackf}|${reset}  ${yeojf}███${boldon}${yeojb}██${reset}${yeojf}█${boldon}${yeojb}██${reset}${yeojf}███${reset}  ${blackf}|${reset}  ${vivif}███${boldon}${vivib}██${reset}${vivif}█${boldon}${vivib}██${reset}${vivif}███${reset}  ${blackf}|${reset}  ${kimlf}███${boldon}${kimlb}██${reset}${kimlf}█${boldon}${kimlb}██${reset}${kimlf}███${reset}
  ${heejf}████${boldon}${heejb}█${reset}${heejf}████${reset}   ${blackf}|${reset}   ${hyunf}████${boldon}${hyunb}█${reset}${hyunf}████${reset}   ${blackf}|${reset}   ${hasef}████${boldon}${haseb}█${reset}${hasef}████${reset}   ${blackf}|${reset}   ${yeojf}████${boldon}${yeojb}█${reset}${yeojf}████${reset}   ${blackf}|${reset}   ${vivif}████${boldon}${vivib}█${reset}${vivif}████${reset}   ${blackf}|${reset}   ${kimlf}████${boldon}${kimlb}█${reset}${kimlf}████${reset}
  ${heejf}█ █ ${boldon}█${reset} ${heejf}█ █${reset}   ${blackf}|${reset}   ${hyunf}█ █ ${boldon}█${reset} ${hyunf}█ █${reset}   ${blackf}|${reset}   ${hasef}█ █ ${boldon}█${reset} ${hasef}█ █${reset}   ${blackf}|${reset}   ${yeojf}█ █ ${boldon}█${reset} ${yeojf}█ █${reset}   ${blackf}|${reset}   ${vivif}█ █ ${boldon}█${reset} ${vivif}█ █${reset}   ${blackf}|${reset}   ${kimlf}█ █ ${boldon}█${reset} ${kimlf}█ █${reset}
    ${heejf}█   █${reset}     ${blackf}|${reset}     ${hyunf}█   █${reset}     ${blackf}|${reset}     ${hasef}█   █${reset}     ${blackf}|${reset}     ${yeojf}█   █${reset}     ${blackf}|${reset}     ${vivif}█   █${reset}     ${blackf}|${reset}     ${kimlf}█   █${reset}
              ${blackf}|               |               |               |               |${reset}

              ${reset}${blackf}|               |               |               |               |${reset}
   ${jinsf}█     █${reset}    ${blackf}|${reset}    ${choef}█     █${reset}    ${blackf}|${reset}    ${yvesf}█     █${reset}    ${blackf}|${reset}    ${chuuf}█     █${reset}    ${blackf}|${reset}    ${gowof}█     █${reset}    ${blackf}|${reset}    ${olivf}█     █${reset}
   ${jinsf}███████${reset}    ${blackf}|${reset}    ${choef}███████${reset}    ${blackf}|${reset}    ${yvesf}███████${reset}    ${blackf}|${reset}    ${chuuf}███████${reset}    ${blackf}|${reset}    ${gowof}███████${reset}    ${blackf}|${reset}    ${olivf}███████${reset}
 ${jinsf}███${boldon}${jinsb}██${reset}${jinsf}█${boldon}${jinsb}██${reset}${jinsf}███${reset}  ${blackf}|${reset}  ${choef}███${boldon}${choeb}██${reset}${choef}█${boldon}${choeb}██${reset}${choef}███${reset}  ${blackf}|${reset}  ${yvesf}███${boldon}${yvesb}██${reset}${yvesf}█${boldon}${yvesb}██${reset}${yvesf}███${reset}  ${blackf}|${reset}  ${chuuf}███${boldon}${chuub}██${reset}${chuuf}█${boldon}${chuub}██${reset}${chuuf}███${reset}  ${blackf}|${reset}  ${gowof}███${boldon}${gowob}██${reset}${gowof}█${boldon}${gowob}██${reset}${gowof}███${reset}  ${blackf}|${reset}  ${olivf}███${boldon}${olivb}██${reset}${olivf}█${boldon}${olivb}██${reset}${olivf}███${reset}
  ${jinsf}████${boldon}${jinsb}█${reset}${jinsf}████${reset}   ${blackf}|${reset}   ${choef}████${boldon}${choeb}█${reset}${choef}████${reset}   ${blackf}|${reset}   ${yvesf}████${boldon}${yvesb}█${reset}${yvesf}████${reset}   ${blackf}|${reset}   ${chuuf}████${boldon}${chuub}█${reset}${chuuf}████${reset}   ${blackf}|${reset}   ${gowof}████${boldon}${gowob}█${reset}${gowof}████${reset}   ${blackf}|${reset}   ${olivf}████${boldon}${olivb}█${reset}${olivf}████${reset}
  ${jinsf}█ █ ${boldon}█${reset} ${jinsf}█ █${reset}   ${blackf}|${reset}   ${choef}█ █ ${boldon}█${reset} ${choef}█ █${reset}   ${blackf}|${reset}   ${yvesf}█ █ ${boldon}█${reset} ${yvesf}█ █${reset}   ${blackf}|${reset}   ${chuuf}█ █ ${boldon}█${reset} ${chuuf}█ █${reset}   ${blackf}|${reset}   ${gowof}█ █ ${boldon}█${reset} ${gowof}█ █${reset}   ${blackf}|${reset}   ${olivf}█ █ ${boldon}█${reset} ${olivf}█ █${reset}
    ${jinsf}█   █${reset}     ${blackf}|${reset}     ${choef}█   █${reset}     ${blackf}|${reset}     ${yvesf}█   █${reset}     ${blackf}|${reset}     ${chuuf}█   █${reset}     ${blackf}|${reset}     ${gowof}█   █${reset}     ${blackf}|${reset}     ${olivf}█   █${reset}
              ${blackf}|               |               |               |               |${reset}

EOF
