#!/bin/env bash

#    Author: Ivo
#  	 Source: http://crunchbang.org/forums/viewtopic.php?pid=150114#p150114
#    ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh

initializeANSI

cat << EOF

 ${boldon}${heejf} █   █ ${reset} ${boldon}${hyunf}█   █ ${reset} ${boldon}${hasef}█   █ ${reset} ${boldon}${yeojf}█   █ ${reset} ${boldon}${vivif}█   █ ${reset} ${boldon}${kimlf}█   █ ${reset} 
 ${boldon}${heejf}  ■ ■  ${reset} ${boldon}${hyunf} ■ ■  ${reset} ${boldon}${hasef} ■ ■  ${reset} ${boldon}${yeojf} ■ ■  ${reset} ${boldon}${vivif} ■ ■  ${reset} ${boldon}${kimlf} ■ ■  ${reset}
 ${boldon}${heejf}  =■=  ${reset} ${boldon}${hyunf} =■=  ${reset} ${boldon}${hasef} =■=  ${reset} ${boldon}${yeojf} =■=  ${reset} ${boldon}${vivif} =■=  ${reset} ${boldon}${kimlf} =■=  ${reset}
 
 ${jinsf} █=@=█ ${reset} ${choef}█=@=█ ${reset} ${yvesf}█=@=█ ${reset} ${chuuf}█=@=█ ${reset} ${gowof}█=@=█ ${reset} ${olivf}█=@=█ ${reset}
 ${jinsf}  ■ ■  ${reset} ${choef} ■ ■  ${reset} ${yvesf} ■ ■  ${reset} ${chuuf} ■ ■  ${reset} ${gowof} ■ ■  ${reset} ${olivf} ■ ■  ${reset}
 ${jinsf}  =■=  ${reset} ${choef} =■=  ${reset} ${yvesf} =■=  ${reset} ${chuuf} =■=  ${reset} ${gowof} =■=  ${reset} ${olivf} =■=  ${reset} 

EOF
