#!/usr/bin/env bash

# ANSI color scheme script featuring PACMAN
# Author: pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=144481#p144481 

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI

cat << EOF

$rst
 ${hasef}  ▄███████▄                ${heejf}  ▄██████▄    ${hyunf}  ▄██████▄    ${yeojf}  ▄██████▄    ${vivif}  ▄██████▄    ${kimlf}  ▄██████▄    
 ${hasef}▄█████████▀▀               ${heejf}▄${whitef}█▀█${heejf}██${whitef}█▀█${heejf}██▄  ${hyunf}▄█${whitef}███${hyunf}██${whitef}███${hyunf}█▄  ${yeojf}▄█${whitef}███${yeojf}██${whitef}███${yeojf}█▄  ${vivif}▄█${whitef}███${vivif}██${whitef}███${vivif}█▄  ${kimlf}▄██${whitef}█▀█${kimlf}██${whitef}█▀█${kimlf}▄
 ${hasef}███████▀      ${whitef}▄▄  ▄▄  ▄▄   ${heejf}█${whitef}▄▄█${heejf}██${whitef}▄▄█${heejf}███  ${hyunf}██${whitef}█ █${hyunf}██${whitef}█ █${hyunf}██  ${yeojf}██${whitef}█ █${yeojf}██${whitef}█ █${yeojf}██  ${vivif}██${whitef}█ █${vivif}██${whitef}█ █${vivif}██  ${kimlf}███${whitef}█▄▄${kimlf}██${whitef}█▄▄${kimlf}█
 ${hasef}███████▄      ${whitef}▀▀  ▀▀  ▀▀   ${heejf}████████████  ${hyunf}████████████  ${yeojf}████████████  ${vivif}████████████  ${kimlf}████████████  
 ${hasef}▀█████████▄▄               ${heejf}██▀██▀▀██▀██  ${hyunf}██▀██▀▀██▀██  ${yeojf}██▀██▀▀██▀██  ${vivif}██▀██▀▀██▀██  ${kimlf}██▀██▀▀██▀██
 ${hasef}  ▀███████▀                ${heejf}▀   ▀  ▀   ▀  ${hyunf}▀   ▀  ▀   ▀  ${yeojf}▀   ▀  ▀   ▀  ${vivif}▀   ▀  ▀   ▀  ${kimlf}▀   ▀  ▀   ▀ 

 ${yvesf}  ▄███████▄                ${jinsf}  ▄██████▄    ${choef}  ▄██████▄    ${chuuf}  ▄██████▄    ${gowof}  ▄██████▄    ${olivf}  ▄██████▄    
 ${yvesf}▄█████████▀▀               ${jinsf}▄${whitef}█▀█${jinsf}██${whitef}█▀█${jinsf}██▄  ${choef}▄█${whitef}███${choef}██${whitef}███${choef}█▄  ${chuuf}▄█${whitef}███${chuuf}██${whitef}███${chuuf}█▄  ${gowof}▄█${whitef}███${gowof}██${whitef}███${gowof}█▄  ${olivf}▄██${whitef}█▀█${olivf}██${whitef}█▀█${olivf}▄
 ${yvesf}███████▀      ${whitef}▄▄  ▄▄  ▄▄   ${jinsf}█${whitef}▄▄█${jinsf}██${whitef}▄▄█${jinsf}███  ${choef}██${whitef}█ █${choef}██${whitef}█ █${choef}██  ${chuuf}██${whitef}█ █${chuuf}██${whitef}█ █${chuuf}██  ${gowof}██${whitef}█ █${gowof}██${whitef}█ █${gowof}██  ${olivf}███${whitef}█▄▄${olivf}██${whitef}█▄▄${olivf}█
 ${yvesf}███████▄      ${whitef}▀▀  ▀▀  ▀▀   ${jinsf}████████████  ${choef}████████████  ${chuuf}████████████  ${gowof}████████████  ${olivf}████████████  
 ${yvesf}▀█████████▄▄               ${jinsf}██▀██▀▀██▀██  ${choef}██▀██▀▀██▀██  ${chuuf}██▀██▀▀██▀██  ${gowof}██▀██▀▀██▀██  ${olivf}██▀██▀▀██▀██
 ${yvesf}  ▀███████▀                ${jinsf}▀   ▀  ▀   ▀  ${choef}▀   ▀  ▀   ▀  ${chuuf}▀   ▀  ▀   ▀  ${gowof}▀   ▀  ▀   ▀  ${olivf}▀   ▀  ▀   ▀ 
$rst

EOF
