#!/usr/bin/env bash

# Author: GekkoP
# Source: http://linuxbbq.org/bbs/viewtopic.php?f=4&t=1656#p33189
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF
 
 ${heejf}███$d▄$t  ${hyunf}███$d▄$t  ${hasef}███$d▄$t  ${yeojf}███$d▄$t  ${vivif}███$d▄$t  ${kimlf}███$d▄$t  ${whitef}███$d▄$t  
 ${heejf}███$d█$t  ${hyunf}███$d█$t  ${hasef}███$d█$t  ${yeojf}███$d█$t  ${vivif}███$d█$t  ${kimlf}███$d█$t  ${whitef}███$d█$t  
 ${heejf}███$d█$t  ${hyunf}███$d█$t  ${hasef}███$d█$t  ${yeojf}███$d█$t  ${vivif}███$d█$t  ${kimlf}███$d█$t  ${whitef}███$d█$t  
 $d${heejf} ▀▀▀   ${hyunf}▀▀▀   ${hasef}▀▀▀   ${yeojf}▀▀▀   ${vivif}▀▀▀   ${kimlf}▀▀▀   ${whitef}▀▀▀  

 ${jinsf}███$d▄$t  ${choef}███$d▄$t  ${yvesf}███$d▄$t  ${chuuf}███$d▄$t  ${gowof}███$d▄$t  ${olivf}███$d▄$t  ${whitef}███$d▄$t  
 ${jinsf}███$d█$t  ${choef}███$d█$t  ${yvesf}███$d█$t  ${chuuf}███$d█$t  ${gowof}███$d█$t  ${olivf}███$d█$t  ${whitef}███$d█$t  
 ${jinsf}███$d█$t  ${choef}███$d█$t  ${yvesf}███$d█$t  ${chuuf}███$d█$t  ${gowof}███$d█$t  ${olivf}███$d█$t  ${whitef}███$d█$t  
 $d${jinsf} ▀▀▀   ${choef}▀▀▀   ${yvesf}▀▀▀   ${chuuf}▀▀▀   ${gowof}▀▀▀   ${olivf}▀▀▀   ${whitef}▀▀▀  
 
EOF
