#!/usr/bin/env bash
# Author: pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=127064#p127064
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF
 
 ${heejf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${hyunf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${hasef}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗
 ${boldon}${heejf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${hyunf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${hasef}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝${reset}
  ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
 ${yeojf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${vivif}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${kimlf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗
 ${boldon}${yeojf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${vivif}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${kimlf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝${reset}

 ${jinsf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${choef}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${yvesf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗
 ${boldon}${jinsf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${choef}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${yvesf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝${reset}
  ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
 ${chuuf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${gowof}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗  ${olivf}╔╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╦╗
 ${boldon}${chuuf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${gowof}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝  ${olivf}╚╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╩╝${reset}
 
EOF
