#!/usr/bin/env bash
# ANSI color scheme script by pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=143700#p143700
# Initializing mod by lolilolicon from Archlinux
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF
 
 ${hasef} ▄      ${heejf}      ▄▄      ${hyunf}      ▄▄      ${yeojf}      ▄▄      ${vivif}      ▄▄      ${kimlf}      ▄▄     
 ${hasef} ███▄▄  ${heejf}   ██▬██▬██   ${hyunf}   ██▬██▬██   ${yeojf}   ██▬██▬██   ${vivif}   ██▬██▬██   ${kimlf}   ██▬██▬██  
 ${hasef} █████▀▀${heejf}     ████     ${hyunf}     ████     ${yeojf}     ████     ${vivif}     ████     ${kimlf}     ████    
 ${hasef} █▀▀    ${heejf}   ▄██  ██▄   ${hyunf}   ▄██  ██▄   ${yeojf}   ▄██  ██▄   ${vivif}   ▄██  ██▄   ${kimlf}   ▄██  ██▄  
 ${hasef} █      ${heejf} ▄▄▄▀█  █▀▄▄▄ ${hyunf} ▄▄▄▀█  █▀▄▄▄ ${yeojf} ▄▄▄▀█  █▀▄▄▄ ${vivif} ▄▄▄▀█  █▀▄▄▄ ${kimlf} ▄▄▄▀█  █▀▄▄▄
 ${hasef}▄█▄     ${heejf} ███▀████▀███ ${hyunf} ███▀████▀███ ${yeojf} ███▀████▀███ ${vivif} ███▀████▀███ ${kimlf} ███▀████▀███
            ${heejf}  ▀  ▀        ${hyunf}  ▀  ▀        ${yeojf}  ▀  ▀        ${vivif}  ▀  ▀        ${kimlf}  ▀  ▀       
$bld
 ${hasef} ▄      ${heejf}      ▄▄      ${hyunf}      ▄▄      ${yeojf}      ▄▄      ${vivif}      ▄▄      ${kimlf}      ▄▄     
 ${hasef} ███▄▄  ${heejf}   ██▬██▬██   ${hyunf}   ██▬██▬██   ${yeojf}   ██▬██▬██   ${vivif}   ██▬██▬██   ${kimlf}   ██▬██▬██  
 ${hasef} █████▀▀${heejf}     ████     ${hyunf}     ████     ${yeojf}     ████     ${vivif}     ████     ${kimlf}     ████    
 ${hasef} █▀▀    ${heejf}   ▄██  ██▄   ${hyunf}   ▄██  ██▄   ${yeojf}   ▄██  ██▄   ${vivif}   ▄██  ██▄   ${kimlf}   ▄██  ██▄  
 ${hasef} █      ${heejf} ▄▄▄▀█  █▀▄▄▄ ${hyunf} ▄▄▄▀█  █▀▄▄▄ ${yeojf} ▄▄▄▀█  █▀▄▄▄ ${vivif} ▄▄▄▀█  █▀▄▄▄ ${kimlf} ▄▄▄▀█  █▀▄▄▄
 ${hasef}▄█▄     ${heejf} ███▀████▀███ ${hyunf} ███▀████▀███ ${yeojf} ███▀████▀███ ${vivif} ███▀████▀███ ${kimlf} ███▀████▀███
            ${heejf}  ▀  ▀        ${hyunf}  ▀  ▀        ${yeojf}  ▀  ▀        ${vivif}  ▀  ▀        ${kimlf}  ▀  ▀      


 ${yvesf} ▄      ${jinsf}      ▄▄      ${choef}      ▄▄      ${chuuf}      ▄▄      ${gowof}      ▄▄      ${olivf}      ▄▄     
 ${yvesf} ███▄▄  ${jinsf}   ██▬██▬██   ${choef}   ██▬██▬██   ${chuuf}   ██▬██▬██   ${gowof}   ██▬██▬██   ${olivf}   ██▬██▬██  
 ${yvesf} █████▀▀${jinsf}     ████     ${choef}     ████     ${chuuf}     ████     ${gowof}     ████     ${olivf}     ████    
 ${yvesf} █▀▀    ${jinsf}   ▄██  ██▄   ${choef}   ▄██  ██▄   ${chuuf}   ▄██  ██▄   ${gowof}   ▄██  ██▄   ${olivf}   ▄██  ██▄  
 ${yvesf} █      ${jinsf} ▄▄▄▀█  █▀▄▄▄ ${choef} ▄▄▄▀█  █▀▄▄▄ ${chuuf} ▄▄▄▀█  █▀▄▄▄ ${gowof} ▄▄▄▀█  █▀▄▄▄ ${olivf} ▄▄▄▀█  █▀▄▄▄
 ${yvesf}▄█▄     ${jinsf} ███▀████▀███ ${choef} ███▀████▀███ ${chuuf} ███▀████▀███ ${gowof} ███▀████▀███ ${olivf} ███▀████▀███
            ${jinsf}  ▀  ▀        ${choef}  ▀  ▀        ${chuuf}  ▀  ▀        ${gowof}  ▀  ▀        ${olivf}  ▀  ▀       
$bld
 ${yvesf} ▄      ${jinsf}      ▄▄      ${choef}      ▄▄      ${chuuf}      ▄▄      ${gowof}      ▄▄      ${olivf}      ▄▄     
 ${yvesf} ███▄▄  ${jinsf}   ██▬██▬██   ${choef}   ██▬██▬██   ${chuuf}   ██▬██▬██   ${gowof}   ██▬██▬██   ${olivf}   ██▬██▬██  
 ${yvesf} █████▀▀${jinsf}     ████     ${choef}     ████     ${chuuf}     ████     ${gowof}     ████     ${olivf}     ████    
 ${yvesf} █▀▀    ${jinsf}   ▄██  ██▄   ${choef}   ▄██  ██▄   ${chuuf}   ▄██  ██▄   ${gowof}   ▄██  ██▄   ${olivf}   ▄██  ██▄  
 ${yvesf} █      ${jinsf} ▄▄▄▀█  █▀▄▄▄ ${choef} ▄▄▄▀█  █▀▄▄▄ ${chuuf} ▄▄▄▀█  █▀▄▄▄ ${gowof} ▄▄▄▀█  █▀▄▄▄ ${olivf} ▄▄▄▀█  █▀▄▄▄
 ${yvesf}▄█▄     ${jinsf} ███▀████▀███ ${choef} ███▀████▀███ ${chuuf} ███▀████▀███ ${gowof} ███▀████▀███ ${olivf} ███▀████▀███
            ${jinsf}  ▀  ▀        ${choef}  ▀  ▀        ${chuuf}  ▀  ▀        ${gowof}  ▀  ▀        ${olivf}  ▀  ▀  
 
EOF
