#!/usr/bin/env bash
# Original: http://crunchbanglinux.org/forums/post/126921/#p126921
# Modified by lolilolicon
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF

${heejf}  ▀▄   ▄▀     ${hyunf} ▄▄▄████▄▄▄    ${hasef}  ▄██▄     ${yeojf}  ▀▄   ▄▀     ${vivif} ▄▄▄████▄▄▄    ${kimlf}  ▄██▄  $rst
 ${heejf} ▄█▀███▀█▄    ${hyunf}███▀▀██▀▀███   ${hasef}▄█▀██▀█▄   ${yeojf} ▄█▀███▀█▄    ${vivif}███▀▀██▀▀███   ${kimlf}▄█▀██▀█▄$rst
 ${heejf}█▀███████▀█   ${hyunf}▀▀███▀▀███▀▀   ${hasef}▀█▀██▀█▀   ${yeojf}█▀███████▀█   ${vivif}▀▀███▀▀███▀▀   ${kimlf}▀█▀██▀█▀$rst
 ${heejf}▀ ▀▄▄ ▄▄▀ ▀   ${hyunf} ▀█▄ ▀▀ ▄█▀    ${hasef}▀▄    ▄▀   ${yeojf}▀ ▀▄▄ ▄▄▀ ▀   ${vivif} ▀█▄ ▀▀ ▄█▀    ${kimlf}▀▄    ▄▀$rst

 $bld${heejf}▄ ▀▄   ▄▀ ▄   ${hyunf} ▄▄▄████▄▄▄    ${hasef}  ▄██▄     ${yeojf}▄ ▀▄   ▄▀ ▄   ${vivif} ▄▄▄████▄▄▄    ${kimlf}  ▄██▄  $rst
 $bld${heejf}█▄█▀███▀█▄█   ${hyunf}███▀▀██▀▀███   ${hasef}▄█▀██▀█▄   ${yeojf}█▄█▀███▀█▄█   ${vivif}███▀▀██▀▀███   ${kimlf}▄█▀██▀█▄$rst
 $bld${heejf}▀█████████▀   ${hyunf}▀▀▀██▀▀██▀▀▀   ${hasef}▀▀█▀▀█▀▀   ${yeojf}▀█████████▀   ${vivif}▀▀▀██▀▀██▀▀▀   ${kimlf}▀▀█▀▀█▀▀$rst
 $bld${heejf} ▄▀     ▀▄    ${hyunf}▄▄▀▀ ▀▀ ▀▀▄▄   ${hasef}▄▀▄▀▀▄▀▄   ${yeojf} ▄▀     ▀▄    ${vivif}▄▄▀▀ ▀▀ ▀▀▄▄   ${kimlf}▄▀▄▀▀▄▀▄$rst


                                     ${whitef}▌$rst

                                   ${whitef}▌$rst

                              ${whitef}    ▄█▄    $rst
                              ${whitef}▄█████████▄$rst
                              ${whitef}▀▀▀▀▀▀▀▀▀▀▀$rst

 ${jinsf}  ▀▄   ▄▀     ${choef} ▄▄▄████▄▄▄    ${yvesf}  ▄██▄     ${chuuf}  ▀▄   ▄▀     ${gowof} ▄▄▄████▄▄▄    ${olivf}  ▄██▄  $rst
 ${jinsf} ▄█▀███▀█▄    ${choef}███▀▀██▀▀███   ${yvesf}▄█▀██▀█▄   ${chuuf} ▄█▀███▀█▄    ${gowof}███▀▀██▀▀███   ${olivf}▄█▀██▀█▄$rst
 ${jinsf}█▀███████▀█   ${choef}▀▀███▀▀███▀▀   ${yvesf}▀█▀██▀█▀   ${chuuf}█▀███████▀█   ${gowof}▀▀███▀▀███▀▀   ${olivf}▀█▀██▀█▀$rst
 ${jinsf}▀ ▀▄▄ ▄▄▀ ▀   ${choef} ▀█▄ ▀▀ ▄█▀    ${yvesf}▀▄    ▄▀   ${chuuf}▀ ▀▄▄ ▄▄▀ ▀   ${gowof} ▀█▄ ▀▀ ▄█▀    ${olivf}▀▄    ▄▀$rst

 $bld${jinsf}▄ ▀▄   ▄▀ ▄   ${choef} ▄▄▄████▄▄▄    ${yvesf}  ▄██▄     ${chuuf}▄ ▀▄   ▄▀ ▄   ${gowof} ▄▄▄████▄▄▄    ${olivf}  ▄██▄  $rst
 $bld${jinsf}█▄█▀███▀█▄█   ${choef}███▀▀██▀▀███   ${yvesf}▄█▀██▀█▄   ${chuuf}█▄█▀███▀█▄█   ${gowof}███▀▀██▀▀███   ${olivf}▄█▀██▀█▄$rst
 $bld${jinsf}▀█████████▀   ${choef}▀▀▀██▀▀██▀▀▀   ${yvesf}▀▀█▀▀█▀▀   ${chuuf}▀█████████▀   ${gowof}▀▀▀██▀▀██▀▀▀   ${olivf}▀▀█▀▀█▀▀$rst
 $bld${jinsf} ▄▀     ▀▄    ${choef}▄▄▀▀ ▀▀ ▀▀▄▄   ${yvesf}▄▀▄▀▀▄▀▄   ${chuuf} ▄▀     ▀▄    ${gowof}▄▄▀▀ ▀▀ ▀▀▄▄   ${olivf}▄▀▄▀▀▄▀▄$rst


                                     ${whitef}▌$rst

                                   ${whitef}▌$rst

                              ${whitef}    ▄█▄    $rst
                              ${whitef}▄█████████▄$rst
                              ${whitef}▀▀▀▀▀▀▀▀▀▀▀$rst

EOF
