#!/usr/bin/env bash
# Author: muzieca
# Source: http://crunchbang.org/forums/viewtopic.php?pid=127509#p127509

my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF

 ${heejf}▀ █${reset} ${boldon}${heejf}█ ▀${reset}   ${hyunf}▀ █${reset} ${boldon}${hyunf}█ ▀${reset}   ${hasef}▀ █${reset} ${boldon}${hasef}█ ▀${reset}   ${yeojf}▀ █${reset} ${boldon}${yeojf}█ ▀${reset}   ${vivif}▀ █${reset} ${boldon}${vivif}█ ▀${reset}   ${kimlf}▀ █${reset} ${boldon}${kimlf}█ ▀${reset} 
 ${heejf}██${reset}  ${boldon}${heejf} ██${reset}   ${hyunf}██${reset}   ${boldon}${hyunf}██${reset}   ${hasef}██${reset}   ${boldon}${hasef}██${reset}   ${yeojf}██${reset}   ${boldon}${yeojf}██${reset}   ${vivif}██${reset}   ${boldon}${vivif}██${reset}   ${kimlf}██${reset}   ${boldon}${kimlf}██${reset}  
 ${heejf}▄ █${reset}${boldon}${heejf} █ ▄ ${reset}  ${hyunf}▄ █ ${reset}${boldon}${hyunf}█ ▄${reset}   ${hasef}▄ █ ${reset}${boldon}${hasef}█ ▄${reset}   ${yeojf}▄ █ ${reset}${boldon}${yeojf}█ ▄${reset}   ${vivif}▄ █ ${reset}${boldon}${vivif}█ ▄${reset}   ${kimlf}▄ █ ${reset}${boldon}${kimlf}█ ▄${reset}  

 ${jinsf}▀ █${reset} ${boldon}${jinsf}█ ▀${reset}   ${choef}▀ █${reset} ${boldon}${choef}█ ▀${reset}   ${yvesf}▀ █${reset} ${boldon}${yvesf}█ ▀${reset}   ${chuuf}▀ █${reset} ${boldon}${chuuf}█ ▀${reset}   ${gowof}▀ █${reset} ${boldon}${gowof}█ ▀${reset}   ${olivf}▀ █${reset} ${boldon}${olivf}█ ▀${reset} 
 ${jinsf}██${reset}  ${boldon}${jinsf} ██${reset}   ${choef}██${reset}   ${boldon}${choef}██${reset}   ${yvesf}██${reset}   ${boldon}${yvesf}██${reset}   ${chuuf}██${reset}   ${boldon}${chuuf}██${reset}   ${gowof}██${reset}   ${boldon}${gowof}██${reset}   ${olivf}██${reset}   ${boldon}${olivf}██${reset}  
 ${jinsf}▄ █${reset}${boldon}${jinsf} █ ▄ ${reset}  ${choef}▄ █ ${reset}${boldon}${choef}█ ▄${reset}   ${yvesf}▄ █ ${reset}${boldon}${yvesf}█ ▄${reset}   ${chuuf}▄ █ ${reset}${boldon}${chuuf}█ ▄${reset}   ${gowof}▄ █ ${reset}${boldon}${gowof}█ ▄${reset}   ${olivf}▄ █ ${reset}${boldon}${olivf}█ ▄${reset}  

EOF
