#!/usr/bin/env bash
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF

 ${vivif}    ██     ${yeojf}      ██   ${heejf}██████████
 ${vivif}  ████     ${yeojf}     ██    ${heejf}        ██
 ${vivif}    ██     ${yeojf}    ██     ${hyunf}██████████
 ${vivif}    ██     ${yeojf}   ██      ${hyunf}        ██
 ${vivif}██████████ ${yeojf}  ██       ${hasef}██████████

 ${kimlf}██████████ ${jinsf}██████████ ${choef}██████████
 ${kimlf}██      ██ ${jinsf}██         ${choef}██    
 ${kimlf}██      ██ ${jinsf}██████████ ${choef}██
 ${kimlf}██      ██ ${jinsf}██         ${choef}██    
 ${kimlf}██████████ ${jinsf}██████████ ${choef}██████████

 ${yvesf}██      ██ ${chuuf}██      ██ ${gowof}██      ██ ${olivf}██      ██ 
 ${yvesf}  ██  ██   ${chuuf}  ██  ██   ${gowof}  ██  ██   ${olivf}  ██  ██   
 ${yvesf}    ██     ${chuuf}    ██     ${gowof}    ██     ${olivf}    ██     
 ${yvesf}    ██     ${chuuf}    ██     ${gowof}  ██  ██   ${olivf}    ██     
 ${yvesf}    ██     ${chuuf}    ██     ${gowof}██      ██ ${olivf}    ██     

EOF
