#!/usr/bin/env bash
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF

${heejf} ▄█▀ █ █ ▀█▄   ${hyunf} ▄█▀ █ █ ▀█▄   ${hasef} ▄█▀ █ █ ▀█▄   ${yeojf} ▄█▀ █ █ ▀█▄   ${vivif} ▄█▀ █ █ ▀█▄   ${kimlf} ▄█▀ █ █ ▀█▄ 
 ${heejf}███  ███  ███  ${hyunf}███  ███  ███  ${hasef}███  ███  ███  ${yeojf}███  ███  ███  ${vivif}███  ███  ███  ${kimlf}███  ███  ███
 ${heejf}█████████████  ${hyunf}█████████████  ${hasef}█████████████  ${yeojf}█████████████  ${vivif}█████████████  ${kimlf}█████████████
 ${heejf} ▀██▄   ▄██▀   ${hyunf} ▀██▄   ▄██▀   ${hasef} ▀██▄   ▄██▀   ${yeojf} ▀██▄   ▄██▀   ${vivif} ▀██▄   ▄██▀   ${kimlf} ▀██▄   ▄██▀ 
 
${boldon} 
 ${heejf} ▄█▀ █ █ ▀█▄   ${hyunf} ▄█▀ █ █ ▀█▄   ${hasef} ▄█▀ █ █ ▀█▄   ${yeojf} ▄█▀ █ █ ▀█▄   ${vivif} ▄█▀ █ █ ▀█▄   ${kimlf} ▄█▀ █ █ ▀█▄ 
 ${heejf}███  ███  ███  ${hyunf}███  ███  ███  ${hasef}███  ███  ███  ${yeojf}███  ███  ███  ${vivif}███  ███  ███  ${kimlf}███  ███  ███
 ${heejf}█████████████  ${hyunf}█████████████  ${hasef}█████████████  ${yeojf}█████████████  ${vivif}█████████████  ${kimlf}█████████████
 ${heejf} ▀██▄   ▄██▀   ${hyunf} ▀██▄   ▄██▀   ${hasef} ▀██▄   ▄██▀   ${yeojf} ▀██▄   ▄██▀   ${vivif} ▀██▄   ▄██▀   ${kimlf} ▀██▄   ▄██▀ 
${reset}

 ${jinsf} ▄█▀ █ █ ▀█▄   ${choef} ▄█▀ █ █ ▀█▄   ${yvesf} ▄█▀ █ █ ▀█▄   ${chuuf} ▄█▀ █ █ ▀█▄   ${gowof} ▄█▀ █ █ ▀█▄   ${olivf} ▄█▀ █ █ ▀█▄ 
 ${jinsf}███  ███  ███  ${choef}███  ███  ███  ${yvesf}███  ███  ███  ${chuuf}███  ███  ███  ${gowof}███  ███  ███  ${olivf}███  ███  ███
 ${jinsf}█████████████  ${choef}█████████████  ${yvesf}█████████████  ${chuuf}█████████████  ${gowof}█████████████  ${olivf}█████████████
 ${jinsf} ▀██▄   ▄██▀   ${choef} ▀██▄   ▄██▀   ${yvesf} ▀██▄   ▄██▀   ${chuuf} ▀██▄   ▄██▀   ${gowof} ▀██▄   ▄██▀   ${olivf} ▀██▄   ▄██▀ 
 
${boldon} 
 ${jinsf} ▄█▀ █ █ ▀█▄   ${choef} ▄█▀ █ █ ▀█▄   ${yvesf} ▄█▀ █ █ ▀█▄   ${chuuf} ▄█▀ █ █ ▀█▄   ${gowof} ▄█▀ █ █ ▀█▄   ${olivf} ▄█▀ █ █ ▀█▄ 
 ${jinsf}███  ███  ███  ${choef}███  ███  ███  ${yvesf}███  ███  ███  ${chuuf}███  ███  ███  ${gowof}███  ███  ███  ${olivf}███  ███  ███
 ${jinsf}█████████████  ${choef}█████████████  ${yvesf}█████████████  ${chuuf}█████████████  ${gowof}█████████████  ${olivf}█████████████
 ${jinsf} ▀██▄   ▄██▀   ${choef} ▀██▄   ▄██▀   ${yvesf} ▀██▄   ▄██▀   ${chuuf} ▀██▄   ▄██▀   ${gowof} ▀██▄   ▄██▀   ${olivf} ▀██▄   ▄██▀ 

EOF
