#!/usr/bin/env bash
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF

${invon}
${heejf}   ▄█     █▄    ${hyunf}   ▄▄     ▄▄    ${hasef}   ▄▄     ▄▄    ${yeojf}   ▄▄     ▄▄    ${vivif}   ▄▄     ▄▄    ${kimlf}   ▄█     █▄   
${heejf} ▄█▀  ▄▄▄  ▀█▄  ${hyunf} ▄█▀  ▄▄▄  ▀█▄  ${hasef} ▄█▀  ▄▄▄  ▀█▄  ${yeojf} ▄█▀  ▄▄▄  ▀█▄  ${vivif} ▄█▀  ▄▄▄  ▀█▄  ${kimlf} ▄█▀  ▄▄▄  ▀█▄ 
${heejf} ██▄▄██▀██▄▄██  ${hyunf} ██▄▄██▀██▄▄██  ${hasef} ██▄▄██▀██▄▄██  ${yeojf} ██▄▄██▀██▄▄██  ${vivif} ██▄▄██▀██▄▄██  ${kimlf} ██▄▄██▀██▄▄██ 
${heejf} ██▀▀█████▀▀██  ${hyunf} ██▀▀█████▀▀██  ${hasef} ██▀▀█████▀▀██  ${yeojf} ██▀▀█████▀▀██  ${vivif} ██▀▀█████▀▀██  ${kimlf} ██▀▀█████▀▀██ 
${heejf} ▀█▄  ▀▀▀  ▄█▀  ${hyunf} ▀█▄  ▀▀▀  ▄█▀  ${hasef} ▀█▄  ▀▀▀  ▄█▀  ${yeojf} ▀█▄  ▀▀▀  ▄█▀  ${vivif} ▀█▄  ▀▀▀  ▄█▀  ${kimlf} ▀█▄  ▀▀▀  ▄█▀ 
${heejf}   ▀█     █▀    ${hyunf}   ▀▀     ▀▀    ${hasef}   ▀▀     ▀▀    ${yeojf}   ▀▀     ▀▀    ${vivif}   ▀▀     ▀▀    ${kimlf}   ▀█     █▀   
${reset}

${invon}
${jinsf}   ▄█     █▄    ${choef}   ▄▄     ▄▄    ${yvesf}   ▄▄     ▄▄    ${chuuf}   ▄▄     ▄▄    ${gowof}   ▄▄     ▄▄    ${olivf}   ▄█     █▄   
${jinsf} ▄█▀  ▄▄▄  ▀█▄  ${choef} ▄█▀  ▄▄▄  ▀█▄  ${yvesf} ▄█▀  ▄▄▄  ▀█▄  ${chuuf} ▄█▀  ▄▄▄  ▀█▄  ${gowof} ▄█▀  ▄▄▄  ▀█▄  ${olivf} ▄█▀  ▄▄▄  ▀█▄ 
${jinsf} ██▄▄██▀██▄▄██  ${choef} ██▄▄██▀██▄▄██  ${yvesf} ██▄▄██▀██▄▄██  ${chuuf} ██▄▄██▀██▄▄██  ${gowof} ██▄▄██▀██▄▄██  ${olivf} ██▄▄██▀██▄▄██ 
${jinsf} ██▀▀█████▀▀██  ${choef} ██▀▀█████▀▀██  ${yvesf} ██▀▀█████▀▀██  ${chuuf} ██▀▀█████▀▀██  ${gowof} ██▀▀█████▀▀██  ${olivf} ██▀▀█████▀▀██ 
${jinsf} ▀█▄  ▀▀▀  ▄█▀  ${choef} ▀█▄  ▀▀▀  ▄█▀  ${yvesf} ▀█▄  ▀▀▀  ▄█▀  ${chuuf} ▀█▄  ▀▀▀  ▄█▀  ${gowof} ▀█▄  ▀▀▀  ▄█▀  ${olivf} ▀█▄  ▀▀▀  ▄█▀ 
${jinsf}   ▀█     █▀    ${choef}   ▀▀     ▀▀    ${yvesf}   ▀▀     ▀▀    ${chuuf}   ▀▀     ▀▀    ${gowof}   ▀▀     ▀▀    ${olivf}   ▀█     █▀   
${reset}

EOF
