#!/usr/bin/env bash
 
my_dir="$(dirname "$0")"
source $(dirname $0)/initialise.sh
initializeANSI
 
cat << EOF

${heejf} ▀▄   ▄▀  ${hyunf} ▀▄   ▄▀  ${hasef} ▀▄   ▄▀  ${yeojf} ▀▄   ▄▀  ${vivif} ▀▄   ▄▀  ${kimlf} ▀▄   ▄▀  
${heejf} ▄▄█▄█▄▄  ${hyunf} ▄▄█▄█▄▄  ${hasef} ▄▄█▄█▄▄  ${yeojf} ▄▄█▄█▄▄  ${vivif} ▄▄█▄█▄▄  ${kimlf} ▄▄█▄█▄▄  
${heejf}█$w██████${heejf}██ ${hyunf}█$w██████${hyunf}██ ${hasef}█$w██████${hasef}██ ${yeojf}█$w██████${yeojf}██ ${vivif}█$w██████${vivif}██ ${kimlf}█$w██████${kimlf}██ 
${heejf}█$w██████${heejf}██ ${hyunf}█$w██████${hyunf}██ ${hasef}█$w██████${hasef}██ ${yeojf}█$w██████${yeojf}██ ${vivif}█$w██████${vivif}██ ${kimlf}█$w██████${kimlf}██ 
${heejf}█$w██████${heejf}██ ${hyunf}█$w██████${hyunf}██ ${hasef}█$w██████${hasef}██ ${yeojf}█$w██████${yeojf}██ ${vivif}█$w██████${vivif}██ ${kimlf}█$w██████${kimlf}██ 
${heejf} ▀▀▀▀▀▀▀  ${hyunf} ▀▀▀▀▀▀▀  ${hasef} ▀▀▀▀▀▀▀  ${yeojf} ▀▀▀▀▀▀▀  ${vivif} ▀▀▀▀▀▀▀  ${kimlf} ▀▀▀▀▀▀▀  $bld

${jinsf} ▀▄   ▄▀  ${choef} ▀▄   ▄▀  ${yvesf} ▀▄   ▄▀  ${chuuf} ▀▄   ▄▀  ${gowof} ▀▄   ▄▀  ${olivf} ▀▄   ▄▀  
${jinsf} ▄▄█▄█▄▄  ${choef} ▄▄█▄█▄▄  ${yvesf} ▄▄█▄█▄▄  ${chuuf} ▄▄█▄█▄▄  ${gowof} ▄▄█▄█▄▄  ${olivf} ▄▄█▄█▄▄  
${jinsf}█$w██████${jinsf}██ ${choef}█$w██████${choef}██ ${yvesf}█$w██████${yvesf}██ ${chuuf}█$w██████${chuuf}██ ${gowof}█$w██████${gowof}██ ${olivf}█$w██████${olivf}██ 
${jinsf}█$w██████${jinsf}██ ${choef}█$w██████${choef}██ ${yvesf}█$w██████${yvesf}██ ${chuuf}█$w██████${chuuf}██ ${gowof}█$w██████${gowof}██ ${olivf}█$w██████${olivf}██ 
${jinsf}█$w██████${jinsf}██ ${choef}█$w██████${choef}██ ${yvesf}█$w██████${yvesf}██ ${chuuf}█$w██████${chuuf}██ ${gowof}█$w██████${gowof}██ ${olivf}█$w██████${olivf}██ 
${jinsf} ▀▀▀▀▀▀▀  ${choef} ▀▀▀▀▀▀▀  ${yvesf} ▀▀▀▀▀▀▀  ${chuuf} ▀▀▀▀▀▀▀  ${gowof} ▀▀▀▀▀▀▀  ${olivf} ▀▀▀▀▀▀▀  $rst

EOF
